language: node_js

node_js:
    - 10
    - 8
    - 7
    - 6
    - 5
    - 4

cache:
    yarn: true

branches:
    only:
        - master

before_install:
    - node --version
    - npm --version

install:
    - yarn install

script:
    - yarn example:build
    - yarn test -- --coverage
