environment:
  matrix:
    - node_version: "10"
    - node_version: "8"
    - node_version: "7"
    - node_version: "6"
    - node_version: "5"
    - node_version: "4"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:node_version
  - npm install

build_script:
  - npm run build
  - npm run example:build

test_script:
  - node --version
  - npm --version
  - npm test -- --coverage

cache:
  - node_modules
